# Generated by Django 3.2.7 on 2021-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210919_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB+', 'AB'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB-', 'AB'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], max_length=50, null=True),
        ),
    ]
